### ISSUE TITLE
Dialog dismissed on rotation

### ISSUE THREAD

**Issue by Sleeper9** [javiersantos/MaterialStyledDialogs#19] opened 2016-05-06 22:03 UTC
The About dialog gets dismissed on screen rotation. Is there a way to keep it after orientation change? [See this StackOverflow question](http://stackoverflow.com/questions/7557265/prevent-dialog-dismissal-on-screen-rotation-in-android)

**Comment by ihangulo** [comment] 2016-06-01 07:06
Is there any method to change the height of HeaderDrawable? I want to increase the size a bit more. Thanks.

**Comment by Rainer-Lang** [comment] 2016-07-11 11:19
Any chance that DialogFragment is used to avoid dismissal of dialogs on rotation?

**Comment by searchy2** [comment] 2016-08-06 02:29
This behavior persists even when "setCancellable()" is set to false. This is a bug as sometimes you want to force your user to make a selection when they activate the dialogue. If the user can accidentally cancel the dialogue by rotating their device, it may cause errors with other event processing. For example, if I offer the user the ability to delete a message and popup this dialogue to confirm their deletion, I do not want the process to be canceled half way.

**Comment by searchy2** [comment] 2016-09-23 01:53
I can confirm that this issue is fixed in the latest build. The dialog does not close on rotate. Thank you @javiersantos for the fix!

**Comment by Sleeper9** [comment] 2016-09-23 13:40
Great, I'll test it and close the issue then!

**Comment by Rainer-Lang** [comment] 2016-09-24 15:44
@searchy2 Which commit?

**Comment by javiersantos** [comment] 2016-09-24 15:59
On my side the dialog seems to be closed when the screen is rotated.

Adding `android:configChanges="orientation|screenSize"` in your `<activity>` tag of the `AndroidManifest.xml` file (see [this commit](https://github.com/javiersantos/MaterialStyledDialogs/commit/a3f057a44dfcc8d5d14e640a39a0f094a378ae14)) will avoid dismissal of the dialog (the activity won't be recreated when the screen is rotated).

I know that it isn't the best solution, but it will work as a temporally workaround.

Hope it helps.

**Comment by searchy2** [comment] 2016-09-24 20:21
@rainer-lang If you set setCancellable(false), the dialogue does not close on rotate.

**Comment by javiersantos** [comment] 2017-02-10 08:38
`DialogFrament` is now supported since the 2.1 release. See an example in the [https://github.com/javiersantos/MaterialStyledDialogs/blob/master/app/src/main/java/com/github/javiersantos/materialstyleddialogs/demo/AboutDialog.java](sample app).

**Closed by javiersantos** 2017-02-10 08:38 UTC
Labels: help wanted, question
